# Generated by Django 4.1.1 on 2022-09-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itasset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemnumber', models.CharField(max_length=300)),
                ('assetname', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('price', models.FloatField(max_length=300)),
                ('quantity', models.FloatField(max_length=300)),
                ('borrowersname', models.CharField(max_length=300)),
            ],
        ),
    ]
